FROM debian:bullseye

ENV MYSQL_ROOT_PASSWORD=

RUN apt-get update && \
    apt-get install -y mariadb-server init && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY my.cnf /etc/mysql/my.cnf

EXPOSE 3306

ENTRYPOINT [ "/usr/bin/init", "--" ]

CMD [ "mysqld" ]