FROM debian:bullseye

RUN apt-get update && \
    apt-get install -y mariadb-server tini && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY 50-server.cnf /etc/mysql/mariadb.conf.d/.
COPY init.sql /etc/mysql/init.sql
COPY sql.sh /etc/mysql/sql.sh

RUN chown -R mysql:mysql /var/lib/mysql && chmod -R 755 /var/lib/mysql
RUN chmod +x /etc/mysql/sql.sh

EXPOSE 3306

RUN mkdir -p /run/mysqld

ENTRYPOINT [ "/usr/bin/tini", "--" ]

CMD ./etc/mysql/sql.sh; mysql_install_db; mysqld