FROM debian:bullseye

RUN apt-get update -y && \
    apt-get -y install tini mariadb-client wget curl tar php7.4-fpm php-mysql \
    less && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists*

RUN sed -i "s/listen = .*/listen = 9000/" /etc/php/7.4/fpm/pool.d/www.conf

COPY ./tools/init-wordpress.sh /usr/local/bin/
COPY www.conf /etc/php/7.4/fpm/pool.d/

RUN chmod +x /usr/local/bin/init-wordpress.sh
RUN mkdir -p /run/php && chown -R www-data:www-data /run/php

EXPOSE 9000

ENTRYPOINT [ "/usr/bin/tini", "--" ]

CMD [ "init-wordpress.sh" ]