FROM debian:bullseye

RUN apt-get update && \
    apt-get install -y nginx openssl tini && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN openssl req -newkey rsa:2048 -nodes -x509 -days 3650 \
    -keyout /etc/ssl/private/key.pem -out /etc/ssl/certs/cert.pem \
    -subj "/C=KR/ST=Seoul/O=42 Seoul/OU=Unit/CN=minsepar.42.fr"

COPY ./nginx.conf /etc/nginx/sites-available/minsepar.42.fr

RUN ln -s /etc/nginx/sites-available/minsepar.42.fr /etc/nginx/sites-enabled/

EXPOSE 443

ENTRYPOINT ["/usr/bin/tini", "--"]

CMD ["nginx", "-g", "daemon off;"]